apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
  labels:
    app.kubernetes.io/name: taskmanager
    app.kubernetes.io/part-of: taskmanager-app
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
